
services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    network_mode: bridge
    command: ["redis-server", "--save", "3600", "1", "300", "100", "60", "10000"]
    expose: 
    - 6379:6379
    ports:
    - 6379:6379

  rubbish:
    build: .
    network_mode: bridge
    restart: unless-stopped
    command: node 'App.js'
    volumes: 
      - .:/app
      - /app/node_modules
    links: 
      - redis
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT= 6379
